version: '3.9'

volumes: 
  mysql-store:

services:

# ---------------------------------
# laravelを動かすコンテナ
# ---------------------------------
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src/:/app

# ---------------------------------
# MySQLを動かすコンテナ
# ---------------------------------
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: laravel_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root@localhost
      MYSQL_PASSWORD: yaku
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

  volumes:
  mysql-volume:

# ---------------------------------
# nginxを動かすコンテナ
# ---------------------------------
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
